version: '2'
services:
    marta-app:
        image: marta
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://marta-mysql:3306/marta?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    marta-mysql:
        extends:
            file: mysql.yml
            service: marta-mysql
